language: ruby
rvm:
    - 1.9.3
before_script:
    - mysql -e 'create database lodge_test'
    - cp config/database.test.yml config/database.yml
    - bundle install
script:
    - RAILS_ENV=test bundle exec rake db:migrate --trace
    - RAILS_ENV=test bundle exec rake spec --trace
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/512ba096c71f9f9634ae
  on_success: change  # options: [always|never|change] default: always
  on_failure: always  # options: [always|never|change] default: always
  on_start: false     # default: false
